# docker-compose.yml (Updated)
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    # This line tells Docker Compose to load variables from the .env file
    env_file:
      - .env